### ISSUE TITLE
Update to L5.7

### ISSUE THREAD

**Issue by rjsworking** [rinvex/laravel-repositories#180]
Hi

Is is possible to update the develop branch to L5.7?

Thanks in advance

**Comment by maherelgamil** [comment]
@Omranic  please accept my pull request to support laravel 5.7 #183

**Comment by Omranic** [comment]
@maherelgamil please re-submit the PR to the `develop` branch.
Nothing should be merged into `master` directly, `develop` is the right branch to go, [CONTRIBUTION TIPS](https://github.com/rinvex/laravel-repositories/blob/master/CONTRIBUTING.md)

**Comment by maherelgamil** [comment]
@Omranic  ok :)

**Comment by Omranic** [comment]
Merged, thank you.
