### ISSUE TITLE
Call to undefined method Illuminate\\Events\\Dispatcher::fire()

### ISSUE THREAD

**Issue by Edrard** [rinvex/laravel-repositories#190]
"message": "Call to undefined method Illuminate\\Events\\Dispatcher::fire()",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/vhosts/ez.pcontrol.info/http/vendor/rinvex/laravel-repositories/src/Traits/Cacheable.php",
    "line": 187,

Please change 
$this->getContainer('events')->fire($this->getRepositoryId().'.entity.cache.flushed', [$this]);

to

$this->getContainer('events')->dispatch($this->getRepositoryId().'.entity.cache.flushed', [$this]);

**Comment by hotrush** [comment]
Maybe @Omranic can do this? I can make a pr if you can merge?

**Comment by Omranic** [comment]
Fixed in 93b129768eb340095802df953285b0c0ba86e649
