### ISSUE TITLE
Supports Laravel 6.0

### ISSUE THREAD

**Issue by Daespinosag** [rinvex/laravel-repositories#199]
it is possible to start with support for Laravel 6.0 ?

**Comment by socramjunio2** [comment]
Hello,

I also need support for laravel 6, did anyone qualify?

**Comment by smartmall-it** [comment]
please add support for laravel 6

**Comment by Omranic** [comment]
All packages are now updated, enjoy!
Thank you for your patience 🙂

**Comment by Yannik-Slym** [comment]
Hello @Omranic 

it's not functionnal like this, method like "array_forget" are removed.

=> https://laravel.com/docs/6.x/upgrade#helpers

**Comment by Omranic** [comment]
@Yannik-Slym fixed in a new release, double check please..
